version: '3.8'

services:
  # Serviço do banco de dados PostgreSQL
  shortb-db:
    image: postgres:15
    container_name: shortb-db
    ports:
      - "5432:5433" # Mapeia porta local 5432 para 5433 no container
    environment:
      POSTGRES_USER: "dba" # Usuário do banco
      POSTGRES_PASSWORD: "dba" # Senha do banco
      POSTGRES_DB: "ShortDB" # Nome do banco
      TZ: "America/Sao_Paulo" # Fuso horário
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistência dos dados
    networks:
      - shortbeyond-network

  # Serviço Adminer para gerenciar o banco via interface web
  shortb-adminer:
    image: adminer
    container_name: shortb-adminer
    ports:
      - "8080:8080" # Porta de acesso ao Adminer
    depends_on:
      - shortb-db # Depende do banco estar ativo
    networks:
      - shortbeyond-network

  # Serviço da API da aplicação
  shortb-api:
    image: beyondtest/shortb-api:latest
    container_name: shortb-api
    ports:
      - "3333:3333" # Porta de acesso à API
    environment:
      PORT: "3333"
      DATABASE_URL: "postgres://dba:dba@shortb-db:5432/ShortDB?sslmode=disable" # String de conexão com o banco
      JWT_SECRET: "vaiplaneta" # Chave secreta para tokens JWT
    depends_on:
      - shortb-db # Depende do banco estar ativo
    networks:
      - shortbeyond-network

  # Serviço web front-end
  shortb-web:
    image: beyondtest/shortb-web:latest
    container_name: shortb-web
    ports:
      - "80:80" # Porta de acesso ao front-end
    depends_on:
      - shortb-api # Depende da API estar ativa
    networks:
      - shortbeyond-network

# Volume para persistência dos dados do banco
volumes:
  postgres_data:

# Rede compartilhada entre os containers
networks:
  shortbeyond-network:
    driver: bridge
