apiVersion: v1
kind: Pod
metadata:
  name: shortbeyond
  labels:
    app: shortbeyond
spec:
  containers:
    # Container do banco de dados PostgreSQL
    - name: shortb-db
      image: postgres:15
      ports:
        - containerPort: 5432
          hostPort: 5433 # Mapeia porta do host para o container
      env:
        POSTGRES_USER: "dba" # Usuário do banco
        POSTGRES_PASSWORD: "dba" # Senha do banco
        POSTGRES_DB: "ShortDB" # Nome do banco
        TZ: "America/Sao_Paulo" # Fuso horário
      volumeMounts:
        - mountPath: /var/lib/postgresql/data # Diretório dentro do container
          name: db-data # Volume associado

    # Container Adminer para gerenciar o banco via interface web
    - name: shortb-adminer
      image: adminer
      ports:
        - containerPort: 8080
          hostPort: 8080

    # Container da API da aplicação
    - name: shortb-api
      image: beyondtest/shortb-api:hotfix
      ports:
        - containerPort: 3333
          hostPort: 3333
      env:
        PORT: "3333" # Porta da API
        DATABASE_URL: "postgres://dba:dba@shortb-db:5432/ShortDB?sslmode=disable" # Conexão com banco
        JWT_SECRET: "vaiplaneta" # Chave JWT

    # Container do front-end web
    - name: shortb-web
      image: beyondtest/shortb-web:latest
      ports:
        - containerPort: 80
          hostPort: 80

  # Volume persistente para o banco de dados
  volumes:
    - name: db-data
      hostPath:
        path: /var/lib/shortbeyond-db # Diretório no host
        type: DirectoryOrCreate # Cria diretório se não existir
